TinyUrlTest/TinyUrlTest/Models/TinyUrl/UrlMap.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel;
using System.Linq.Expressions;

namespace TinyUrlTest.Models.TinyUrl
{ 
    public class UrlMap
    {
        public const int MaxDigitNumber = 5;       
        public static readonly int MaxId = GetMaxId();      
        public int Id { get; set; }
             
        [Required]
        [DisplayName("Long  Url")]
        public string LongUrl { get; set; }

        [StringLength(MaxDigitNumber)]
        [DisplayName("Short Url")]
        [RegularExpression("^[0-9a-zA-Z ]+$", ErrorMessage = "Use characters and numbers only")]
        public string TinyUrl { get; set; }
       
        public const string MapCollection = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        
        public static string GetTinyUrlById(int n) {
            n = n - 1;
            List<char> tinyUrl = new List<char>();
            if (n == 0) return "a";
            while (n >   0)
            {
                tinyUrl.Add(MapCollection[n % 62]);
                n = n / 62;
            }
            tinyUrl.Reverse();

            return string.Join("", tinyUrl.ToArray());
        }

        public static int GetIdByTinyUrl(string tinyUrl)
        {       
            int id = 0; 
            for (int i = 0; i < tinyUrl.Count(); i++)
            {
                if ('a' <= tinyUrl[i] && tinyUrl[i] <= 'z')
                    id = id * 62  +tinyUrl[i] - 'a';
                if ('A' <= tinyUrl[i] && tinyUrl[i] <= 'Z')
                    id = id * 62  +tinyUrl[i] - 'A' + 26;
                if ('0' <= tinyUrl[i] && tinyUrl[i] <= '9')
                    id = id * 62  + tinyUrl[i] - '0' + 52;
            }
            return id +1 ;
        }

        public static int GetMaxId()
        {
            var maxId = Int32.MaxValue;
            var maxTinyUrlForInt32 = GetTinyUrlById(maxId);

            //Check if const MaxDigitNumber is set right for Int32
            var isMaxDigitNumberTooBigForInt32 = maxTinyUrlForInt32.Count() < MaxDigitNumber ||
                String.Compare(maxTinyUrlForInt32, new String('9', MaxDigitNumber)) < 0;
           
            if (isMaxDigitNumberTooBigForInt32)
            {
                var maxDigitNumberForInt32 = maxTinyUrlForInt32.Count() - 
                    (maxTinyUrlForInt32 == new String('9', maxTinyUrlForInt32.Count()) ? 0 : 1);

                throw new System.ArgumentException("const int UrlMap.MaxDigitNumber = " +
                    MaxDigitNumber + " can't be more than " + maxDigitNumberForInt32);                
            }
           
            maxId = GetIdByTinyUrl(new String('9', MaxDigitNumber));                
           
            return maxId;
          
        }

        public static string MakeUrlWithProtocol(string url){
            url = url.ToLower();
            if (!(url.Length > 5 && (url.StartsWith("http://") || url.StartsWith("https://"))))
            {
                url = "http://" + url;
            }
            return url;
        }
    }
}

TinyUrlTest/TinyUrlTest/Controllers/TinyUrlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using TinyUrlTest.Models.TinyUrl;
using TinyUrlTest.Repositories.TinyUrl;
using TinyUrlTest.ViewModels;
using TinyUrlTest.Services;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace TinyUrlTest.Controllers
{
    public class TinyUrlController : Controller
    {
        public const int ConstItemsPerPage = 10;        
        private ITinyUrlRepository<UrlMap, int> _repo;


        public TinyUrlController(ITinyUrlRepository<UrlMap, int> repo)
       {
           _repo = repo;
       }


        public ActionResult RedirectToFullUrl(string id)
        {
            var tinyUrl = id;
            if (tinyUrl.Count() > UrlMap.MaxDigitNumber)
                return View("RedirectError",
                            (object)("Wrong alias. Alias max length can't be more than " +  UrlMap.MaxDigitNumber));
               

            var cacheService = new CacheService();
            var urlMap = cacheService.GetOrSet("TinyUrl-"+ tinyUrl, 
                                () =>_repo.GetUrlMapById(UrlMap.GetIdByTinyUrl(tinyUrl)));
            if (urlMap != null)
            {
                return Redirect(urlMap.LongUrl);
            }
            else
            {
                return View("RedirectError",
                            (object)("No Long Url for alias '" + tinyUrl + "' was not found. Not able to redirect."));
            }
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult DeleteUrlMap(int id)
        {
            var cacheService = new CacheService();
            string tinyUrl = UrlMap.GetTinyUrlById(id);
            var urlMap = cacheService.Remove<UrlMap>("TinyUrl-" + tinyUrl);
            var result = _repo.DeleteUrlMap(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Home()
        {
            ViewBag.Host = Request.Url.Scheme + "://" + Request.Url.Authority + "/";
            return View(new UrlMap());
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult MakeTinyUrl(UrlMap urlMap)
        {           
           urlMap.LongUrl = UrlMap.MakeUrlWithProtocol(urlMap.LongUrl);
           var result = IsUrlExists(urlMap.LongUrl);
       
            if (result)
            {
                urlMap = _repo.AddUrlMap(urlMap);
            }
            else {
                urlMap.Id = -3;
            }
            return Json( urlMap, JsonRequestBehavior.AllowGet);
       }

      
        [NonAction]
        public bool IsUrlExists(string FullUrl)
        {
            string url = UrlMap.MakeUrlWithProtocol(FullUrl);
            bool result;
            try
            {
                HttpWebRequest request = WebRequest.Create(url) as HttpWebRequest;
                request.Method = "HEAD";
                HttpWebResponse response = request.GetResponse() as HttpWebResponse;
                result = (response.StatusCode == HttpStatusCode.OK);
               
            }
            catch
            {
                result = false;
            }
            return result;
        }

        public ActionResult Index(int id = 1, int itemsPerPage = ConstItemsPerPage)
        {         
            var pageNumber = id;
            var urlMaps = _repo.GetUrlMaps(pageNumber, itemsPerPage);
            var urlMapsCount = _repo.GetUrlMapsCount();

            var vm = new UrlMapsViewModel(){
                    Host = Request.Url.Scheme + "://" + Request.Url.Authority + "/",
                    PageNumber = pageNumber,
                    PagesNumber = (int)Math.Ceiling((double)urlMapsCount / itemsPerPage),
                    ItemsPerPage = itemsPerPage,
                    UrlMaps = urlMaps,
                    UrlMapsCount = urlMapsCount
                };

            if (Request.IsAjaxRequest())
            {
                return Json(new {gridInfo = vm }, JsonRequestBehavior.AllowGet);
            }
           
            else return View(vm);
        }
    }
}

TinyUrlTest/TinyUrlTest/Views/TinyUrl/Home.cshtml
@model UrlMap
@using TinyUrlTest.Models.TinyUrl;
@{
    ViewBag.Title = "Home";
}
@section MainContent{

@using (Html.BeginForm("MakeTinyUrl", "Home", FormMethod.Post))
{
<div class="row" style="padding-top:40px;">
    <div class="col-xs-12 col-md-8">
       <h4><b> Make Tiny URL</b></h4>
      <div class ="home-box">
        <label>Enter a long URL to make tiny</label><br />
        @Html.ValidationMessageFor(m => m.LongUrl)
        <div class="input-group" style="margin-bottom:15px;">          
            @Html.TextBoxFor(m => m.LongUrl, new { @class = "form-control", placeholder = " Enter a long URL to make tiny" })
            <span class="input-group-btn">
                <button class="btn btn-primary btn-take-tiny-url" id="btnLogin" type="button">Go!</button>
            </span>
        </div>
        <br/>
        <label>Custom alias (optional, may contain letters, numbers)</label><br/>        
        @Html.ValidationMessageFor(m => m.TinyUrl)
        <div class="input-group">           
            <span class="input-group-addon bg-primary">@ViewBag.Host</span>
            @Html.TextBoxFor(m => m.TinyUrl, new { @class = "form-control", placeholder = " Custom alias (optional)" })
        </div>      
       </div>
        <div id="tiny-url-info" style="padding-top:60px;"></div>
    </div>    
</div>
}
}

@section Scripts {
<script type="text/javascript" src="http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>
@Scripts.Render("~/Scripts/jquery.validate.min.js")
@Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")

<script>
    $(function () {
        $(".container").on("click", ".btn-take-tiny-url", function (event) {

            $("#tiny-url-info").empty();
            var form = $(this).closest('form');
            form.validate();
            form.valid();
            if (!form.valid()) { return false };

            $.post("/TinyUrl/MakeTinyUrl", form.serialize(), function (data) {
                var urlMap = data;

                if (urlMap.Id == 0) {
                    BootstrapDialog.alert({
                        title: 'Warning',
                        message: "This alias was taken.",
                        type: BootstrapDialog.TYPE_WARNING,
                    });                  
                }
                else if (urlMap.Id == -2) {
                    BootstrapDialog.alert({
                        title: 'Warning',
                        message: "No free alias. Try in 2-3 hours.",
                        type: BootstrapDialog.TYPE_WARNING,
                    });
                }

                else if (urlMap.Id == -3) {
                    BootstrapDialog.alert({
                        title: 'Error',
                        message: "Long URL is not valid or dead",
                        type: BootstrapDialog.TYPE_DANGER,
                    });
                }

                else if (urlMap.Id == -1) {                  
                    BootstrapDialog.alert({
                        title: 'Error',
                        message: "Not able to make timy url. Try again.",
                        type: BootstrapDialog.TYPE_DANGER,
                    });
                }

                else {
                    $("#TinyUrl").val(urlMap.TinyUrl);
                    var control = $("#tmpSuccess").tmpl(urlMap);                
                    $("#tiny-url-info").append(control);
                }
            });
            return false;
        });
    })

</script>

<script type="text/html" id="tmpSuccess">
    <div style="padding-top:15px;">
        <h4><b>Tiny URL was created!</b></h4>
        <div class="home-box">
            <p> Tiny URL for <a href="${FullUrl}">${LongUrl}</a> was created.</p>
            <p> The following URL: <a href="@ViewBag.Host${TinyUrl}" target="_blank">@ViewBag.Host${TinyUrl}</a> open in new window </p>
        </div>
    </div>
</script>
}

TinyUrlTest/TinyUrlTest/Views/TinyUrl/Index.cshtml
@using TinyUrlTest.ViewModels;
@model UrlMapsViewModel
@{
    ViewBag.Title = "Admin";
   
    int[] options = {4, 8, 10, 20, 30, 40, 50, 100};
}

@section MainContent{

<div class="row">

    <div class="col-sm-8 col-xs-6">
        <ul class="pagination pagination-md  pull-left">

            @for (int i = 1; i <= Model.PagesNumber; i++)
            {
                <li @Html.Raw(Model.PageNumber == i ? "class='active'" : "")>
                    @Html.ActionLink(i.ToString(), "Index", new { id = i, itemsPerPage = Model.ItemsPerPage })
                </li>
            }
        </ul>
    </div>

    @using (Html.BeginForm("Index", "TinyUrl"))
    {
        <div class="col-xs-6 col-sm-4  text-right">
           
            <div class="pull-right" style="vertical-align:bottom;padding-top:19px;">
             
                <div class="input-group pull-right">
                    <span class="input-group-addon">per page</span>
                    <select class="form-control select-perpage" name="itemsPerPage" id="itemsPerPage" style="width:70px;margin-right:0px; ">
                        @foreach (var option in options)
                        {
                            <option @(option == Model.ItemsPerPage ? "selected=\"selected\"" : "")>@option</option>
                        }
                    </select>
                </div>
            </div>
        </div>
    }
</div>   

<div class="row hidden-xs visible-md visible-lg" style="margin-top:40px;">
    <div class="col-xs-2 col-xs-12"><h4><b>Id</b></h4></div>
    <div class="col-xs-12 col-md-2"><h4><b>Alias</b></h4></div>
    <div class="col-xs-7 col-xs-9 "><h4><b>Tiny URL / Long URL </b></h4></div>
    <div class="col-md-1 col-xs-3">
        <a class="btn btn-default btn-sm btn-refresh-grid" title="Refresh grid">
            <span class="glyphicon glyphicon-refresh"></span>
        </a>
    </div>
</div>
<hr class="hr-grid" />

@if (Model.UrlMapsCount == 0){
    <div class="row">
        <div class="col-xs-12 text-center">No data</div>       
    </div>
    <hr/>
}
else
{
    foreach (var m in Model.UrlMaps)
    {
        <div class="row">
            <div class="col-md-2 col-xs-12"><text class="hidden-md hidden-lg"><u>Id:</u></text> <span>@m.Id</span></div>
            <div class="col-md-2 col-xs-12"><text class="hidden-md hidden-lg"><u>Alias:</u></text> <a href="@Model.Host@m.TinyUrl"><span>@m.TinyUrl</span></a></div>
            <div class="col-md-7 col-xs-12">
                <text class="hidden-md hidden-lg"><u>Tiny url:</u> </text>
                <a href="@Model.Host@m.TinyUrl"><span>@Model.Host@m.TinyUrl</span></a><br />
                <text class="hidden-md hidden-lg"><u>Long url:</u> </text>
                <a href="@m.LongUrl"><span>@m.LongUrl</span></a>               
            </div>            
            <div class="col-md-1 col-xs-12"><br class="hidden-md hidden-lg"/>                
                <a class="btn btn-sm  btn-default  link-delete-url-map"
                   href="@Url.Action( "DeleteUrlMap", "TinyUrl", new { id = m.Id })" title="Delete tiny url">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
            </div>
        </div>        
         <hr />
    }
}
}  

@section Scripts {
<script>
        $(function () {
          
            $(".container").on("click", ".btn-refresh-grid", function (event) {
                event.preventDefault();
                var target = $(".hr-grid");
                window.location.href = "/TinyUrl/Index/1?itemsPerPage=" + $("#itemsPerPage").val();
                return;
            });

            $(".select-perpage").change(function (e) {

                $(this).closest("form").submit();
            });

            $("li.active a").click(function (e) {
                e.preventDefault();
            });

        $(".container").on("click", ".link-delete-url-map", function (event) {
            event.preventDefault();

            var deleteLinkObj = $(this);
            var parent = deleteLinkObj.closest('.row');
            var spans = parent.find("span");
            var links = parent.find("a");
            var urlId = spans.eq(0).text();
            var alias = spans.eq(1).text();
            var tinyUrl = "<br/>Tiny URL:<br/>" + links.eq(1).html();
            var fullUrl = "<br/>Long URL:<br/>" +links.eq(2).html();
                                
            var temp = "<div id ='divModalDelete'>Do you want to delete this record?<br/><br/>Id:  " + urlId +
                                "<br/>Alias:  " + alias + tinyUrl + fullUrl +"</div>";
            BootstrapDialog.show({
                title: 'Confirmation',
                message: temp,

                buttons: [{
                    label: 'Yes',
                    action: function (dialogItself) {

                        $.post(deleteLinkObj[0].href, function (data) {
                            if (data > 0) {
                                parent.next().remove();
                                parent.remove();
                                dialogItself.close();
                            }
                            else {

                                dialogItself.close();
                                temp.find("#divModalDelete")
                                    .html("Not able to delete tiny url" + name)
                                    .addClass("text-danger");
                                var dialogInstance1 = new BootstrapDialog({
                                    title: 'Error',
                                    type: BootstrapDialog.TYPE_DANGER,
                                    message: temp.html()
                                });
                                dialogInstance1.open();
                            }
                        });
                    }

                }, {
                    label: 'No',
                    action: function (dialogItself) {
                        dialogItself.close();
                    }
                }]
            });
        });

    })
</script>

}  

TinyUrlTest/TinyUrlTest/Views/TinyUrl/RedirectError.cshtml
@model string
@{
    ViewBag.Title = "Redirect Error";
}

@section MainContent{

<div class=" alert alert-danger text-center" style="margin-top:100px;padding:40px 0px;">
    @Model
</div>

}